### ISSUE TITLE
Документация и вики

### ISSUE THREAD

**Issue by themanyfaceddemon** [AngelsAndDemonsDM/DM-Bot#48]
# Описание задачи
Необходимо всю документацию перенести на [wiki](https://github.com/AngelsAndDemonsDM/DM-Bot/wiki)
Необходимо оформить вики

**УБЕДИТЕЛЬНАЯ ПРОСЬБА ПИНГОВАТЬ @themanyfaceddemon КОГДА СДЕЛАЛИ ПР ВЫПОЛНЯЮЩИЙ TODO!!!**

## TODO:
- [ ] Перенести всю папку Libriary_Of_Ruina в [wiki](https://github.com/AngelsAndDemonsDM/DM-Bot/wiki) и после удалить папку
- [ ] Перенести всю папку Docs
- [ ] Сделать гайд как устанавливать и запускать
- [x] Сделать гайд как работать с git
- [ ] Не сойти с ума

**Comment by themanyfaceddemon** [comment]
Гайд сделан
https://github.com/AngelsAndDemonsDM/DM-Bot/wiki/Подготовка-окружения
https://github.com/AngelsAndDemonsDM/DM-Bot/wiki/Как-начать-работу-с-репозиторием
https://github.com/AngelsAndDemonsDM/DM-Bot/wiki/Первые-изменения

**Comment by themanyfaceddemon** [comment]
Закрыто из-за нового репозитория для Wiki
